### ISSUE TITLE
Required hardware

### ISSUE THREAD

**Issue by CosminLazar** [plaksnor/HASS-JablotronSystem#1]
Is there any special hardware required to connect to the alarm system, or will just a regular USB cable get the job done?

Have you thought about placing this nice component in HACS (https://community.home-assistant.io/t/custom-component-hacs/121727)?

Thank you for the nice work!

**Comment by tomdh76** [comment]
I have a regular usb cable which works for arming and disarming. I do not have any sensors though but I do not think it has something do with the cable

**Comment by CosminLazar** [comment]
Super, thank you so much for your answer!
